Event/urls.py
from django.urls import path
from . import views


app_name = 'Event'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.register, name='register'),
    path('login_user/', views.LoginView.as_view(), name='login_user'),
    path('logout_user/', views.LogoutView.as_view(), name='logout_user'),
    path('<int:pk>/', views.EventDetail.as_view(), name='detail'),
    path('create_event/', views.EventCreate.as_view(), name='create_event'),
    path('event/<int:pk>/', views.EventUpdate.as_view(), name='update_event'),
    path('<int:pk>/delete_event/', views.EventDelete.as_view(), name='delete_event'),
    path('<int:pk>/favorite_event/', views.favorite_event, name='favorite_event'),
]

EventNotifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('Event.urls')),
    path('', include('Event.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('whats_new/', views.whats_new, name='whats_new'),
]

Event/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


CHOICES = (
        ('Conferences', 'Conferences'),
        ('Workshops and classes','Workshops and classes'),
        ('Awards and competitions', 'Awards and competitions'),
        ('Festivals and parties', 'Festivals and parties'),
        ('Birthday', 'Birthday'),
    )

class Event(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    detail = models.TextField(max_length=2000)
    event_type = models.CharField(max_length=100, choices=CHOICES)
    event_logo = models.FileField()
    date = models.DateField(blank=True)
    time = models.TimeField(blank=True)

    def get_absolute_url(self):
        return reverse('Event:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

Home/models.py
from django.db import models

# Create your models here.

Event/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.checks import messages
from .models import Event


class EventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ['title', 'event_type', 'detail', 'event_logo', 'date', 'time']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username' : forms.TextInput(attrs={'placeholder': 'Username'}),
            'email' : forms.TextInput(attrs={'placeholder': 'Email'}),
            'password' : forms.TextInput(attrs={'placeholder': 'Password'})
            }

Event/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserForm
from .models import Event
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from . import tasks


# AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'
    context_object_name = 'events'
    template_name = 'index.html'

    def get_queryset(self):
        print(self.request.user)
        return Event.objects.filter(user=self.request.user)


class EventCreate(LoginRequiredMixin, CreateView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'
    model = Event
    fields = ['title', 'event_type', 'detail', 'event_logo', 'date', 'time']
    template_name = 'create_event.html'

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(EventCreate, self).form_valid(form)


class EventDetail(LoginRequiredMixin, generic.DetailView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'
    model = Event
    template_name = 'detail.html'


class EventUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'
    model = Event
    fields = ['title', 'event_type', 'detail', 'event_logo', 'date', 'time']
    template_name = 'create_event.html'

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(EventUpdate, self).form_valid(form)


class EventDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'
    model = Event
    success_url = reverse_lazy('Event:index')


def favorite_event(request, event_id=None):
    event = get_object_or_404(Event, id=event_id)
    try:
        if event.is_favorite:
            event.is_favorite = False
        else:
            event.is_favorite = True
        event.save()
    except (KeyError, Event.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


class LogoutView(View):
    def get(self, request):
        logout(request)
        form = UserForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, 'login.html', context)


class LoginView(View):
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                tasks.send_email('patel1451@gmail.com', 'welcome'+username)
                return redirect('Event:index')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})

    def get(self, request):
        return render(request, 'login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('Event:index')
    context = {
        "form": form,
    }
    return render(request, 'register.html', context)

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
    return render(request, 'html/index.html')


def about(request):
    return render(request, 'html/about.html')


def contact(request):
    return render(request, 'html/contact.html')


def whats_new(request):
    return render(request, 'html/updates.html')

Event/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Event Notifier{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'logo.jpg' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Event:index' %}">Event Notifier</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block events_active %}{% endblock %}"><a href="{% url 'Event:index' %}"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Events</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'Event:index' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'Event:create_event' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Event
                    </a>
                </li>
                <li>
                    <a href="{% url 'Event:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Event/templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Event Notifier{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'logo.jpg' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Event:index' %}">Event Notifier</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'Event:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'Event:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Event/templates/create_event.html
{% extends 'base.html' %}
{% block title %}Add a New Event{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Event</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Event Notifier?</h3>
                    <p>Event Notifier is an app that allows you to add and store all of your events on the cloud.</p>
                    <!--<h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>-->
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

Event/templates/detail.html
{% extends 'base.html' %}
{% block title %}{{ Event }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Event:detail' event.id %}">
                        {% if event.event_logo %}
                            <img src="{{ event.event_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ event.title }} <small>{{ event.type }}</small></h1>
                    <h2>{{ event.detail }}</h2>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

Event/templates/form_template.html
{% load widget_tweaks %} 
<div class="form-group">
    <label class="control-label col-sm-2">Title</label>
    <div class="col-sm-6">
        {% render_field form.title type="text" class="form-control" id="id_title" placeholder="Title" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.title.errors }}</span>
    </div>

    <label class="control-label col-sm-2">Date</label>
    <div class="col-sm-6">
        {% render_field form.date type="date" class="form-control" id="id_date" placeholder="date" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.date.errors }}</span>
    </div>

    <label class="control-label col-sm-2">Time</label>
    <div class="col-sm-6">
        {% render_field form.time type="time" class="form-control" id="id_time" placeholder="time" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.time.errors }}</span>
    </div>

    <label class="control-label col-sm-2">Event Type</label>
    <div class="col-sm-6">
        {% render_field form.event_type type="text" class="form-control" id="id_type" placeholder="type" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.event_type.errors }}</span>
    </div>
    
    <label class="control-label col-sm-2">Event Logo</label>
    <div class="col-sm-6">
        {% render_field form.event_logo type="file" class="form-control" id="id_logo" placeholder="logo" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.event_logo.errors }}</span>
    </div>
    
    <label class="control-label col-sm-2">Detail</label>
    <div class="col-sm-6">
        {% render_field form.detail type="text" class="form-control" id="id_detail" placeholder="detail" %}
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.detail.errors }}</span>
    </div>
    
</div>

Event/templates/index.html
{% extends 'base.html' %}
{% block event_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Events -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Events</h3>
        </div>
        {% if events %}
            {% for event in events %}
                <div class="col-sm-4 col-lg-4">
                    <div class="thumbnail">
                        <a href="{% url 'Event:detail' event.id %}">
                            <img src="{{ event.event_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ event.title }}</h2>
                            <h4>{{ event.detail }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'Event:detail' event.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            
                            <!-- View Details -->
                            <a href="{% url 'Event:update_event' event.id %}" class="btn btn-primary btn-sm" role="button">Edit</a>


                            <!-- Delete Album -->
                            <form action="{% url 'Event:delete_event' event.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="event_id" value="{{ event.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Event -->
                            <a href="{% url 'Event:favorite_event' event.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if event.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'Event:create_event' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Event
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are Events -->
    {% if event %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Events</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Event Title</th>
                                    <th>Event Type</th>
                                    <th>Detail</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr>
                                        <td>{{ event.title }}</td>
                                        <td>{{ event.event_type }}</td>
                                        <td>{{ event.detail }}</td>
                                        <td>
                                            <a href="{% url 'Event:favorite' event.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if event.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

Event/templates/login.html
{% extends 'base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Event:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Event:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Event/templates/register.html
{% extends 'base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'register_form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'Event:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Event/templates/register_form_template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-6">
            {{field}}
        </div>
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
    </div>
{% endfor %}